version: '3'

services:

    caddy:
        image: siwecos/caddy
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./caddy/Caddyfile:/etc/Caddyfile:ro
            - caddy_certs:/root/.caddy
            - ./caddy/blockpage.html:/srv/blockpage.html:ro

    siwecos-business-layer:
        image: siwecos/siwecos-business-layer:latest
        restart: always
        depends_on:
            - mariadb
            - redis
        volumes:
            - ./service-account.json:/var/www/html/service-account.json
        environment:
            - APP_URL=http://siwecos-business-layer
            - APP_DEBUG=false
            - CORE_API_SCAN_START_URL=http://172.17.0.1:8000/api/v2/scan
            - LOG_CHANNEL=stderr
            - DB_HOST=mariadb
            - DB_DATABASE=siwecos-bla
            - DB_USERNAME=siwecos_user
            - DB_PASSWORD=changeme
            - FILESYSTEM_DRIVER=gcs
            - GOOGLE_CLOUD_STORAGE_BUCKET=
            - TECHNICAL_SUPPORT_MAIL=
            - MAIL_DRIVER=smtp
            - MAIL_HOST=
            - MAIL_USERNAME=
            - MAIL_PASSWORD=
            - MAIL_PORT=587
            - MAIL_ENCRYPTION=tls
            - LOGSTASH_HOST=logstash

    logstash:
        image: docker.elastic.co/logstash/logstash:7.1.1
        # build:
        #     context: logstash/
        #     args:
        #         ELK_VERSION: 7.1.1
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"

    mariadb:
        image: mariadb
        restart: always
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=changeme
            - MYSQL_DATABASE=siwecos-bla
            - MYSQL_USER=siwecos_user
            - MYSQL_PASSWORD=changeme

    redis:
        image: redis
        restart: always

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    db:
    caddy_certs:
